name: CI-CD Agendamiento

on:
  push:
    branches:
      - main

jobs:

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:

      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Ejecutar pruebas backend
        run: npm run test

      - name: Compilar backend
        run: npm run build

  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:

      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Compilar frontend
        run: npm run build